### ISSUE TITLE
Geräteart ändern

### ISSUE THREAD

**Issue by tremotik** [rudyberends/homebridge-loxone-proxy#101]
Moin, ich habe mehrere Steckdosen welche aber als Schalter angezeigt werden. Wie kann ich das Mapping auf Steckdosen ändern?

**Comment by rudyberends** [comment]
kannst du mir einen Screenshot der App und einen Screenshot der Loxoneconfig einer bestimmten Steckdose schicken?

**Comment by tremotik** [comment]
Hatte auch schon versucht die Namen auf outlet zu ändern kein erfolg
![Unbenannt](https://github.com/user-attachments/assets/6086517e-eb37-4131-886c-feba432a5022)
![image](https://github.com/user-attachments/assets/98966d4a-2041-463a-afe7-3c26b821c75c)

**Comment by rudyberends** [comment]
Sie verwenden Steckdosensymbole für Ihre Steckdosen. Entweder direkt oder über die separate Kategorie.

Könnten Sie die neueste Betaversion ausprobieren? (v1.11.0-beta.2) Diese Version versucht, (Schalter-)Elemente Steckdosen zuzuordnen, wenn das Symbol auf eine Steckdose eingestellt ist.

Möglicherweise müssen Sie den Cache Ihres Homebridge-Elements leeren, da sich das ursprüngliche Schalterelement möglicherweise noch im Cache befindet.

Bitte lassen Sie mich wissen, ob dies bei Ihnen funktioniert.

**Comment by tremotik** [comment]
Die Steckdosen hat er nun erkannt. Dafür findet er nun Räume nicht und ein paar elemente

**Comment by rudyberends** [comment]
Könnten Sie es mit der neuesten Beta noch einmal versuchen?

**Comment by tremotik** [comment]
Habe es heute mal ausprobiert und es läuft perfekt. Besten dank
