### ISSUE TITLE
Garage Doors out of PushButton and TextState

### ISSUE THREAD

**Issue by 350d** [rudyberends/homebridge-loxone-proxy#23]
Hello! I have some weird way of garage doors implementation with push button and text state of the door status.

```
{
    "13a66542-02a7-cdf9-ffffeab7a19e67ff": {
        "cat": "13a6626c-0155-2f75-ffffc1fe7adce52a",
        "defaultIcon": "IconsFilled/garage-closed-2.svg",
        "defaultRating": 1,
        "details": {
            "jLockable": false,
            "type": 71
        },
        "isFavorite": true,
        "isSecured": false,
        "name": "Parking",
        "restrictions": 0,
        "room": "13a6623e-0195-2031-ffffc1fe7adce52a",
        "states": {
            "active": "13a66542-02a7-cdf9-ffffeab7a19e67ff"
        },
        "type": "Pushbutton",
        "uuidAction": "13a66542-02a7-cdf9-ffffeab7a19e67ff"
    },
    "1843878b-0039-94a9-fffffe21e7f5dd5d": {
        "cat": "13a6626c-0155-2f75-ffffc1fe7adce52a",
        "defaultIcon": null,
        "defaultRating": 0,
        "isFavorite": false,
        "isSecured": false,
        "name": "Parking Gates",
        "restrictions": 0,
        "room": "13a6623e-0195-2031-ffffc1fe7adce52a",
        "states": {
            "iconAndColor": "1843878b-0039-94aa-fffffe21e7f5dd5d",
            "textAndIcon": "1843878b-0039-94a9-fffffe21e7f5dd5d"
        },
        "type": "TextState",
        "uuidAction": "1843878b-0039-94a9-fffffe21e7f5dd5d"
    }
}
```

<img width="248" alt="Screenshot 2023-08-07 at 10 32 32" src="https://github.com/rudyberends/homebridge-loxone-proxy/assets/429208/1c5314c2-cce2-4a8a-8d4c-5e44ffb2f45e">

Is it possible to manage to create normal Garage Doors in HomeKit out of these two properties?

**Comment by rudyberends** [comment]
Would you be able to share a screenshot of how these items are setup in Loxone config?
You might want to put your Loxone config to English before you take the screenshot. :-)

**Comment by 350d** [comment]
Output - you mean UI? Its a push button, just circle with no state.
<img width="248" alt="Screenshot 2023-08-07 at 10 32 32" src="https://github.com/rudyberends/homebridge-loxone-proxy/assets/429208/01e3e841-f456-4e6f-b83e-06a918b79cd0">

**Comment by 350d** [comment]
It's a shared building garage. Door will open, wait 10-15 seconds and close automatically. There is some feedback from the gates available with this logic from screenshot but it doesn't work at this time (something broken I guess), so, I have CLOSE and BUSY states only (should be OPEN if it will be fixed).
![IMG_3002](https://github.com/rudyberends/homebridge-loxone-proxy/assets/429208/8cae3f43-34a3-4275-9265-ce2ce0b69e8f)

**Comment by rudyberends** [comment]
no, I mean virtual output. I guess you use some form of virtual output (network command) to open and close the doors right?
Based on the UI screenshot, I guess it is based on a toggle switch, as your pushbutton in the ui is also a toggle. So, every time you press it the doors change state right? (when open, they close, when closed they will)

**Comment by 350d** [comment]
Correct, I guess this is it in config right here:
![IMG_3003](https://github.com/rudyberends/homebridge-loxone-proxy/assets/429208/9514c8d4-6292-464c-8d46-64352dbfef16)

**Comment by 350d** [comment]
This GET http request fire every time I click that button and gates status changes and update with another get request (every 10 seconds I guess) 
![](https://user-images.githubusercontent.com/429208/258741409-0141db0b-a86f-4ca5-90fb-eba988730e6a.JPG)

**Comment by rudyberends** [comment]
So, to answer your question. Yes, there is enough information available in your setup to turn it into a homekit garage door.

Implementing this into my plugin would require a custom gate item which would specifically map your items to a homebridge garage door. There should be custom configuration options for the mappings, that will have to be on a naming convention. I do not think this will ever be used by anyone except for your very specific use case. So I don't think we should implement this.

However, looking at your setup, and all the info you gave me, I don't see why your setup cannot be changed to make use of the gate/garage function block. It will work flawlessly in the loxone app, and you will also have the functionality you want in HomeKit using this plugin. I am happy to help you out if you need any help in setting this up on the Loxone side.

**Comment by 350d** [comment]
I've created fake Garage Door with [my own plugin](https://github.com/350d/homebridge-http-garage-doors) and single Loxone API call.
