### ISSUE TITLE
Window state

### ISSUE THREAD

**Issue by MephistoJB** [rudyberends/homebridge-loxone-proxy#30]
I have those: https://shop.loxone.com/enen/window-handle-air.html

They are not recognized by this app right now. Is there a chance to add this?

**Comment by rudyberends** [comment]
No problem. I will add it, but you will test it for me, as I don't have one myself.

We need a HomeKit accessory to map the item to. HomeKit has a contact sensor accessory;

https://developers.homebridge.io/#/service/ContactSensor

Will this give you what you want?

**Comment by MephistoJB** [comment]
That’s not a problem. I will test it.

The Contact Sensor would be one possibility,

Another would be this:

https://developers.homebridge.io/#/service/Window

I think the advantage could be to make a „tilt“ state possible. But I good with both.

Thank you :)

And just to make it easier. Do you speak German? As a loxone user this is not unlikely :)
Am 18. Aug. 2023, 10:21 +0200 schrieb Rudy Berends ***@***.***>:

**Comment by MephistoJB** [comment]
Oh I just saw, that you edited your message. So I think Window would be better if possible. If you need something else please ask.

I uploaded a picture of the channels. I think it would be the best to grab the position channel.

<img width="879" alt="Bildschirmfoto 2023-08-18 um 17 13 06" src="https://github.com/rudyberends/homebridge-loxone-proxy/assets/6490305/8dbb63f7-782c-4932-978f-4d8bc092362c">

**Comment by rudyberends** [comment]
Kannst du mir ein bisschen helfen? Wie sieht dieser item in der Loxone config aus? 

Die Ein- und Ausgänge der handle AIR sind mit einem item verbunden und diesen item wollen wir in ein Homekit-Zubehör verwandeln. Könnten Sie einen Screenshot der Konfiguration teilen?

**Comment by MephistoJB** [comment]
oh ok, verstanden. Allerdings ist dieses Item nicht nur mit einem Fenster verbunden. Vielmehr laufen alle Fenster eines Raumes dort zusammen. Es ist das hier: https://www.loxone.com/dede/kb/fenster-tuer-ueberwachung/

Das sieht bei mir so aus: 
<img width="200" alt="Bildschirmfoto 2023-08-18 um 21 04 38" src="https://github.com/rudyberends/homebridge-loxone-proxy/assets/6490305/b87df2e2-54f4-4756-9c2b-f687b8764db0">

Kriegst du das auseinander in der config Datei du ausliest?

**Comment by rudyberends** [comment]
Kein Problem. Möchten Sie diesen item auch wie in der StructureFile angegeben freigeben? Dieses Element ist wahrscheinlich vom Typ „WindowMonitor“. Für mich reicht nur der Abschnitt, der ein einzelnes item enthält

Sie können die Strukturdatei im Webbrowser über die folgende URL anfordern;
http://192.168.1.200/data/LoxAPP3.json

Sie müssen die IP-Adresse durch die IP-Adresse Ihres eigenen Miniservers ersetzen.

**Comment by MephistoJB** [comment]
"1b81e1a4-0193-69cd-ffff7eeb839295e7": {
      "name": "Fenster",
      "type": "WindowMonitor",
      "uuidAction": "1b81e1a4-0193-69cd-ffff7eeb839295e7",
      "room": "121b0d0e-00ef-1115-ffff7eeb839295e7",
      "cat": "121b0d0e-00a1-0fe8-ffff7eeb839295e7",
      "defaultRating": 10,
      "isFavorite": false,
      "isSecured": false,
      "restrictions": 0,
      "details": {
        "jLockable": false,
        "windows": [
          {
            "name": "Wohnzimmer Links",
            "installPlace": "Wohnzimmer Fenster",
            "room": "121b0d0e-00ef-1115-ffff7eeb839295e7"
          },
          {
            "name": "Wohnzimmer Rechts",
            "installPlace": "Wohnzimmer Fenster",
            "room": "121b0d0e-00ef-1115-ffff7eeb839295e7"
          },
          {
            "name": "TerassentÃ¼r",
            "installPlace": "Wohnzimmer TerassentÃ¼r",
            "room": "121b0d0e-00ef-1115-ffff7eeb839295e7"
          }
        ]
      },
      "states": {
        "numOpen": "1b81e1a4-0193-69c4-08ffacc0b76bf512",
        "numClosed": "1b81e1a4-0193-69c6-0affacc0b76bf512",
        "numTilted": "1b81e1a4-0193-69c5-09ffacc0b76bf512",
        "numOffline": "1b81e1a4-0193-69c7-0bffacc0b76bf512",
        "numLocked": "1b81e1a4-0193-69c8-0cffacc0b76bf512",
        "numUnlocked": "1b81e1a4-0193-69c9-0dffacc0b76bf512",
        "windowStates": "1b81e1a4-0193-69ba-ffffacc0b76bf512"
      }
    }

**Comment by rudyberends** [comment]
Ich habe den Funktionsbaustein „WindowMonitor“ im Code implementiert. Alle Fenster und Türen in diesem Block werden in HomeBridge in ein Kontaktsensorelement umgewandelt. Dieser item hat einen offenen/geschlossenen Status. Ein Kippen ist hiermit also nicht möglich. (dann zeigt der item „offen“ an).

Die Funktionalität ist in der neuesten Beta (1.3.0 Beta) enthalten. Vielleicht können Sie sie testen?

Ist das etwa das, was Sie sich vorgestellt haben?

**Comment by rudyberends** [comment]
Ich habe eine neue Beta-Version veröffentlicht. Dieser enthält einen Debug-Block. Könnten Sie noch einmal testen und dann die Ausgabe der Debug-Abschnitte teilen? Sie sollten im Protokoll erscheinen. Können Sie auch testen, was passiert, wenn sich der Status ändert, indem Sie ein Fenster öffnen oder schließen?

**Comment by MephistoJB** [comment]
Habe ein bisschen rumgespielt. Das ist das Ergebnis:
```

ITEM: Wohnzimmer Links
ITEM ID: 0
Full Message: 1,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Rechts
ITEM ID: 1
Full Message: 1,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Terassentür
ITEM ID: 2
Full Message: 1,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Links
ITEM ID: 0
Full Message: 1,4,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Rechts
ITEM ID: 1
Full Message: 1,4,1
ITEM Entry: 4
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Terassentür
ITEM ID: 2
Full Message: 1,4,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Links
ITEM ID: 0
Full Message: 1,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Rechts
ITEM ID: 1
Full Message: 1,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Terassentür
ITEM ID: 2
Full Message: 1,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Links
ITEM ID: 0
Full Message: 4,1,1
ITEM Entry: 4
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Rechts
ITEM ID: 1
Full Message: 4,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Terassentür
ITEM ID: 2
Full Message: 4,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Links
ITEM ID: 0
Full Message: 1,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Rechts
ITEM ID: 1
Full Message: 1,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Terassentür
ITEM ID: 2
Full Message: 1,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Links
ITEM ID: 0
Full Message: 4,1,1
ITEM Entry: 4
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Rechts
ITEM ID: 1
Full Message: 4,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Terassentür
ITEM ID: 2
Full Message: 4,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Links
ITEM ID: 0
Full Message: 2,1,1
ITEM Entry: 2
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Rechts
ITEM ID: 1
Full Message: 2,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Terassentür
ITEM ID: 2
Full Message: 2,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Links
ITEM ID: 0
Full Message: 4,1,1
ITEM Entry: 4
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Rechts
ITEM ID: 1
Full Message: 4,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Terassentür
ITEM ID: 2
Full Message: 4,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Links
ITEM ID: 0
Full Message: 1,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Rechts
ITEM ID: 1
Full Message: 1,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Terassentür
ITEM ID: 2
Full Message: 1,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Links
ITEM ID: 0
Full Message: 1,4,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Rechts
ITEM ID: 1
Full Message: 1,4,1
ITEM Entry: 4
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Terassentür
ITEM ID: 2
Full Message: 1,4,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Links
ITEM ID: 0
Full Message: 1,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Rechts
ITEM ID: 1
Full Message: 1,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Terassentür
ITEM ID: 2
Full Message: 1,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Links
ITEM ID: 0
Full Message: 1,4,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Rechts
ITEM ID: 1
Full Message: 1,4,1
ITEM Entry: 4
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Terassentür
ITEM ID: 2
Full Message: 1,4,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Links
ITEM ID: 0
Full Message: 1,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Wohnzimmer Rechts
ITEM ID: 1
Full Message: 1,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
ITEM: Terassentür
ITEM ID: 2
Full Message: 1,1,1
ITEM Entry: 1
Homebridge itemstate: 1
!!!!!!! DEBUG !!!!!!
```

**Comment by rudyberends** [comment]
Danke fürs Testen. Können Sie es noch einmal mit der neuesten Version versuchen? (Ich habe es versehentlich in die Master-Version 1.3.0 verschoben, aber ich denke, dass es auf diese Weise in Ordnung ist.)

**Comment by MephistoJB** [comment]
Funktioniert großartig. Vielen Dank!!!!!

Falls mir noch was auffällt geb ich laut. Danke
