### ISSUE TITLE
kamera vom Eingangsbaustein

### ISSUE THREAD

**Issue by andy0172** [rudyberends/homebridge-loxone-proxy#37]
Hi. Danke für die tolle Weiterentwicklung. Seit der neusten Version wird mit sich eine Kamera „Eingang“ angezeigt. Ich denke automatisch aus dem Eingangsbaustein der Loxone. Dort hat ich den jmpeg stream hinterlegt von meiner webcam an der Haustür. Loxone zeigt auch das Video und das Standbild an sobald jemand klingelt. Leider klappt es in HomeKit nicht. Er bekommt keine Verbindung zur Kamera. 

Wie muss die Einstellung in Loxone sein damit das ganze klappt?

**Comment by rudyberends** [comment]
Derzeit werden benutzerdefinierte Kameras vom Plugin nicht unterstützt.

Könnten Sie einen Screenshot zeigen, wie es in der Loxone-config aussieht? Und könnten Sie auch den StruktureFile dieses Item teilen?

Mit diesen Informationen können wir feststellen, ob wir dies im Plugin umsetzen können.

**Comment by rudyberends** [comment]
Vielleicht möchten Sie die neueste Betaversion ausprobieren. (v1.3.1-beta.3) Ich habe einige Änderungen am Code vorgenommen, um "IntercomV1 custom cameras" zu unterstützen.

Ich kann es selbst nicht testen. Vielleicht können Sie diese Funktion testen?

**Comment by andy0172** [comment]
Ja hab ich gesehen, hab schon getestet leider ohne Erfolg. Versuche nächste Woche mal die Dateien hier hochzuladen. Ansonsten kann ich anbieten dass wir Remote auf mein System schauen und direkt probieren wenn das hilft.

**Comment by andy0172** [comment]
Es funktioniert jetzt, vielen Dank noch mal!!
