### ISSUE TITLE
Support for temperature/humidity sensor

### ISSUE THREAD

**Issue by jrieken** [rudyberends/homebridge-loxone-proxy#49]
First one all thank you for this great project. 

At home I have loxone [climate sensors](https://shop.loxone.com/enen/room-climate-sensor-tree-white.html) for humidity and temperature. I can configure the latter but not the former so this issue a feature request to also support temperature sensor. Today, my workaround is the following config

```
"InfoOnlyAnalogAlias": {
    "Humidity": "Temp"
}
```

This maps my _Temp_erature sensors - works well but all values are in relative percentages and not degrees ;-) As far as my understanding goes `src/loxone/items/InfoOnlyAnalog.ts` needs another tweak to support the temperature service/characteristic

**Comment by rudyberends** [comment]
No problem. The latest release has support for temperature sensors. There is a new alias for it in the config.
Does this work for you?

**Comment by jrieken** [comment]
> Does this work for you?

Didn't get to try this yet. Loxone is at the weekend place. Will report back once I have it tested. Thanks for the rapid fix!

**Comment by rudyberends** [comment]
Yes it works for me, but please let me know if you are having issues with it. You just need to configure the new TEMP alias for your sensors.
