### ISSUE TITLE
Intercom doorbell and speaking not working

### ISSUE THREAD

**Issue by sgasser** [rudyberends/homebridge-loxone-proxy#52]
Hi,

Intercom camera is working great! 
Doorbell and speaking is not working. 
I can not see any log or error.
Is this a technical limitation? 

Thank you

**Comment by rudyberends** [comment]
Doorbell should work. What kind of intercom do you have?

I wanted to implement 2way audio and HomeKit secure video, but i did not finish it yet. The basic HomeKit code is already there, so thats why you see this in the HomeKit ui. I probably should not have pushed this to the Main repository yet.

**Comment by sgasser** [comment]
Doorbell works about 50% of the time. 

I have the "old" intercom.  

Thank you for the work.

**Comment by rudyberends** [comment]
If you put HomeBridge in debug mode, do you see a log entry for every time you press the doorbell? I don't think this is an issue with the plugin, as I cannot reproduce this.

**Comment by rudyberends** [comment]
feel free to reopen the issue if you want to work on this
