### ISSUE TITLE
Question on 2 way updates

### ISSUE THREAD

**Issue by daveo2k** [rudyberends/homebridge-loxone-proxy#53]
Is there any way to have 2 way updates for lights within a lighting controller?  For example the integration will pull in the moods from a lighting controller but also the individual light circuits, dimmers, RGBW etc.  This then allows you to togle them on and off etc via ther Home app which is great but if you do that the status is then lost.  So if I switch a spot light on via the Home app it goes on, then i reopen the Home app the device will show as off and to switch it off you need to switch it on then off again.  I'm assuming this is a limitation on the miniserver rather than anything else but just thought i'd ask incase i'd missed something!

**Comment by rudyberends** [comment]
Hi,

Could you try the latest release to see if this solves your issues?

**Comment by daveo2k** [comment]
Thanks I’ll upgrade and test in the morning.
While I’ve got you…is there a way of excluding certain device types?

**Comment by daveo2k** [comment]
I’ll upgrade and tear in the morning.
Is there a way of excluding certain device types from being imported,

**Comment by rudyberends** [comment]
There is now ;-)

The latest beta has a feature to exclude items based on a setting in the config. You can add items you want to exclude in a comma separated list.

**Comment by daveo2k** [comment]
That’s great 2 way updates seem to be working 👍 for some reason it’s intermittent in my RGBW extensions…
If you need a guinea pig for testing let me know.

**Comment by daveo2k** [comment]
exclusion working great, you can ignore the RGBW thing...for what ever reason if you toggle the device on from the Home app it doesn't go on but if you select and colour and raise the brightness it does so maybe a Home app issue rather than anything else.
Don't suppose you know if there's a way to customise the Alarm modes once they are in Homebridge do you?

**Comment by rudyberends** [comment]
I am closing this issue as it was related to 2 way updates and this is now working.

If you have ideas on improvements on the Alarm modes, please create another issue and let me know on how you would like this to be handled or mapped
