### ISSUE TITLE
Alarm switch not working

### ISSUE THREAD

**Issue by jan-sevcik-snadnee** [rudyberends/homebridge-loxone-proxy#68]
Hi, using v 1.7.0 im not Ábel to switch alarm mode from the HomeKit. When I click to the panel, it only start processing and never finishes.

**Comment by rudyberends** [comment]
The latest beta (1.7.0 beta 3) has support for setting the alarm from HomeKit.
Could you try this version?

It's not perfect, because I use a delayed ARM. So the homekit switch flics back to the previous setting until the delayed timeout is over. I will fix this in the coming days.

**Comment by jan-sevcik-snadnee** [comment]
It works like perfectly! Thank you very much for the super fast update.
