### ISSUE TITLE
Feature idea: House mood switch

### ISSUE THREAD

**Issue by jan-sevcik-snadnee** [rudyberends/homebridge-loxone-proxy#69]
Would it be possible to control the house moods (e.g. Day/Morning/Evening/Night from the HomeKit? It would be a great automation trigger. Thanks

**Comment by rudyberends** [comment]
Could you tell me more about this setup? Are these moods configured as switches? How does this work in Loxone?

**Comment by jan-sevcik-snadnee** [comment]
I have operating modes like Morning/Day/Evenning/Night that are the main triggers for the automation. For example on certain time (alarm) the house switch to the Morning mode (doors unlock, Window shades open) and it would be great to add some extra devices through Homekit. 

![Screenshot_2024-01-10 16 42 18](https://github.com/rudyberends/homebridge-loxone-proxy/assets/60385208/bfa06604-93f9-424c-869e-096a1d30c7be)

**Comment by rudyberends** [comment]
So, basically what you are requesting is the implementation of Radio Switches.

The latest beta is an attempt at that. It creates a Group with the name of the Radio Switch. Inside the group it creates a Switch for each operating mode. It works just like Loxone, so only one switch can be active at the same time.

You can then manually create HomeKit automations that are triggered by the switches, or you can set the switches by HomeKit automations.

I will probably tune it a little bit, but you can try this beta in the meantime. Please let me know if this is something you can work with.

**Comment by rudyberends** [comment]
Thank you for testing. I will keep it in beta for a short while, as there were some code changes to the core of the plugin which might affect some other Items. Please let me know if you have any issues with it. Also, If you have more suggestions for improvement, please create another issue.
