### ISSUE TITLE
Automatikbeschattung

### ISSUE THREAD

**Issue by FalseIsNotTrue1981** [rudyberends/homebridge-loxone-proxy#7]
Zuerst möchte ich mich bei Ihnen für die Implementierung einer neuen HomeKit Schnittstelle bedanken.

Ich würde mich freuen wenn es möglich wäre auch die Automatikbeschattung zu integrieren.

**Comment by rudyberends** [comment]
Kein Problem. Das sollte nicht zu schwer zu implementieren sein. Ich werde diese Woche eine Veröffentlichung mit Unterstützung dafür veröffentlichen. Vielleicht kannst du es testen und mir Feedback geben?

**Comment by FalseIsNotTrue1981** [comment]
Super, vielen Dank.

Ich teste gerne und gebe dann Feedback.

**Comment by FalseIsNotTrue1981** [comment]
Vielen Dank für die Implementierung.

Es funktioniert soweit alles super.

Eine Kleinigkeit ist mir noch aufgefallen. Die Position der Jalousie ist im Gegensatz zu Loxone invertiert (Home 80% <-> Lox 20%).

**Comment by rudyberends** [comment]
Die Warnungen können abgefangen werden, indem die Werte in Richtung Homekit begrenzt werden. Ich werde dies in der nächsten Version hinzufügen. Ich vermute, dass es für den Betrieb jetzt keine Rolle spielt.

Ist das Problem mit den Prozentzahlen wirklich ein Problem? Sowohl Loxone als auch Homekit arbeiten mit einem Prozentsatz. HomeKit ist zu 100% vollständig offen. Loxone ist zu 100% komplett geschlossen. Im Beispiel (80/20) könnte es also sein, dass Homekit „80% offen“ und Loxone „20% geschlossen“ sagt. Ist das so oder ist das wirklich falsch?

**Comment by FalseIsNotTrue1981** [comment]
zu 1.
Vielen Dank für das abfangen der Warnungen. Im Betrieb scheint es keine Rolle zu spielen.

zu 2.
Ich denke es liegt wie von dir beschrieben an der unterschiedlichen Interpretation der prozentualen Werte zwischen Lox und Home. Somit passt es wie es ist.

Ich hätte noch eine Frage zu den Aliassen. Wo vergebe ich diese in der Lox Config?

**Comment by rudyberends** [comment]
Die Alias-Mappings habe ich von den anderen Plugins übernommen. Ich persönlich bin kein Fan davon. Ich versuche das immer noch mit Kategorien zu lösen. Im Moment funktioniert das gut.

Jeder loxone item hat einen item type. Basierend auf diesem Typ können wir die meisten items automatisch verknüpfen. zum Beispiel haben die kürzlich implementierten Automatikbeschattung den Typ "Jalousie"

Es gibt jedoch einige items, die einen gemeinsamen InfoOnlyAnalog- oder InfoOnlyDigital Typ verwenden. Um diese items verknüpfen zu können, benötigen wir etwas anderes. Dies kann beispielsweise namentlich erfolgen. Dies ist die Funktion des Alias.

In meinem eigenen Setup verwende ich beispielsweise für Bewegungsmelder die Namenskonvention Mo01, Mo02 usw. Durch die Angabe des Alias ​​„Mo“ im Plugin für Bewegungsmelder werden alle items mit Mo im Namen als Bewegungsmelder erkannt.

In der Loxone Config geben Sie allen Bewegungsmeldern einen Namen mit der gleichen Konvention. Diese tragen Sie unter „Bezeignung“ bzw. „Beschreibung“ ein. Ist „Beschreibung“ ausgefüllt, dan hat diese Vorrang. Wichtig ist auch, dass in der Visualisierung „verwenden“ angehakt ist. Andernfalls ist das item für das Plugin nicht sichtbar.

Dasselbe gilt für die anderen items. Einzige Ausnahme ist das Türschloss. Wir gehen hier von einem Switch aus. Unter Alias ​​können Sie den vollständigen Namen des Türschlosses angeben. Dadurch wird ein Switch mit diesem Namen als Türschloss verknüpft.

Es gibt 1 zusätzliche undokumentierte Funktion, die ich selbst verwende. Wenn Sie eine IntercomV2 haben, können Sie den Namen des Bewegungsmelders dieser intercom in „IntercomV2“ ändern. Der Bewegungsmelder steht dann als Bewegungsmelder unter der Kameraklingel zur Verfügung. Prinzipiell sollte so Homekit Secure Video möglich sein. Dies muss weiter implementiert werden.

Ich werde dieses issue offen lassen, bis ich eine Version herausgebe, die die Werte einschränkt. Dann schließe ich das issue.
Wenn Sie weitere Wünsche haben, würden Sie dies bitte in einer neuen issue tun? Probleme für die Jalousien können natürlich hier gemeldet werden

**Comment by FalseIsNotTrue1981** [comment]
Vielen Dank für die ausführliche Erklärung.

**Comment by rudyberends** [comment]
fixed with 1b98ee4
