### ISSUE TITLE
Dimmers are linked as switch item

### ISSUE THREAD

**Issue by jslits** [rudyberends/homebridge-loxone-proxy#74]
Hi all,

Out of the box the loxone dimmers are linked to a switch instead of a bulb: is it possible to change this to a bulb afterwards?

I switched over from "Homebridge Loxone Connect" to "Homebridge Loxone Proxy" and noticed the difference.

Thanks for the reply.

Jeroen

**Comment by rudyberends** [comment]
So this is a standalone dimmer item, and not a LightController based dimmer right?

Could you send me a screenshot of such an item in Loxone config?

**Comment by jslits** [comment]
![dimmer](https://github.com/rudyberends/homebridge-loxone-proxy/assets/83949086/367a89d3-58de-4e15-8134-6e7ec4960272)
 type (if I click on the i in loxone config) is "Dimmer (Dim)" for the dimmers being used and "Lichtsturing (Lico)" for the led strips.

**Comment by rudyberends** [comment]
I don't use standalone lightItems myself, so I never noticed this behavior. The latest beta (v1.8.0-beta.2) should map all your dimmers to lightbulbs.

Please let me know if it resolves your issue.

**Comment by jslits** [comment]
that did the trick, thanks rudy
