### ISSUE TITLE
Siri "turn on lights" not working for dimmable lights (just with specific brightness)

### ISSUE THREAD

**Issue by 3limin4tor** [rudyberends/homebridge-loxone-proxy#77]
Hi, i found a strange issue, when i say to siri "Turn on lights" in a room, where there are tunable white led's it wont turn them on actually, in the home app it shows on and 100% brightness for some seconds, then jumps back to the actual state (off). However when telling siri set lights to X% brighness, it works without a problem, but telling siri "turn on lights" not working for lights that are dimmable. 

If you need further information just ask. 

EDIT: Forgot to mention, that within the home app (if you tab directly on the circle with the icon of the light) it works without any issues and turn on on 100% level. Just not working when using siri (doesn't matter if siri is used on iphone, ipad or homepod, same result)

**Comment by rudyberends** [comment]
I cannot reproduce this issue. Could you turn HomeBridge in debug mode and look at the logs to see what happens?
Perhaps you can share the logs here

**Comment by geppertm86** [comment]
Can half agree:
"Siri schalte das Licht in der Küche ein" leave the Dimmable Light "Decke" Off/0 Brightness , the way around the same, "Schalte das Licht in der Küche aus" leaves the Dimmable one on if it was turned on before.

If you say "Hey Siri, schalte Küche Decke ein" it is working as expected.

I tried it also in a Room where only a Dimmable Light is present, same behavior
<img width="998" alt="Bildschirmfoto 2024-02-02 um 15 29 50" src="https://github.com/rudyberends/homebridge-loxone-proxy/assets/102605984/fb478b14-ffd6-4ca8-8b4c-425928d15062">

**Comment by 3limin4tor** [comment]
@geppertm86 Interesting, didn't figured that out, will try it by myself when i arrive home. 
@rudyberends Sorry for the late response, i missed your answer. I will have a deeper look at the weekend and let you know my findings.
