### ISSUE TITLE
https missing?

### ISSUE THREAD

**Issue by PaulmichlJ** [rudyberends/homebridge-loxone-proxy#85]
missing the ability to connect to a miniserver who accepts only secured connection (443)

**Comment by rudyberends** [comment]
I have never tested it with a v2 miniserver, but we can probably make it work. Can you use an ip to connect to the miniserver, or does it have to be an DNS record?

**Comment by PaulmichlJ** [comment]
First of all THANK YOU SO MUCH FOR YOUR REPLY!Yes, I can use an IP with a dedicated port number. For example like 80.120.119.50:8106/ BUT it must be a https connection to pass firewall aso.Sent from my mobile by a dyslexic, sorry for shortened statement  and please ignore any orthographic mistakes ;-)






Mit bestem Gruß,MMst. Jürgen M. Paulmichl, BSc MA____________________________On 2024-02-23, at 14:45, Rudy Berends ***@***.***> wrote:﻿
I have never tested it with a v2 miniserver, but we can probably make it work. Can you use an ip to connect to the miniserver, or does it have to be an DNS record?

**Comment by rudyberends** [comment]
The latest beta has an additional option in the config to enable https/tls. This will connect to the miniserver using https. However, the underlying LXcomunicator expects the certificate to be valid. So you need to connect using the hostname that matches the certificate and the certificate must be signed by a public CA. (not selfsigned).

Could you try it with your setup and let me now if it works for you? I am unable to test it myself.

**Comment by PaulmichlJ** [comment]
Dear Mr. Berends,I just updated your plugin today and would like to thank you very much! The plugin supports https and therefore works perfectly over the internet, through the firewall, etc.! For me, this is an indescribably great next step toward a cross-building smart home solution with HomeKit. Donations will, of course, follow!Sent from my mobile, sorry for shortened statement  and please ignore any orthographic mistakes ;-)Mit bestem Gruß,MMst. Jürgen Paulmichl, BSc MA_____________________________________________________________________________Leutenhofen 30A-6914 HohenweilerAustria/EuropeMobile:+43/699/10017769EMail: ***@***.***_______________________________________________________________________________Disclaimer:This email is confidential and intended solely for the use of the individual to whom it is addressed. Any viewsor opinions presented are solely those of the author and do not necessarily represent those of his company.If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing, or copying of this email is strictly prohibited.Although the sender endeavours to maintain a computer virus free network, the sender does not warrant thatthis transmission is virus-free and will not be liable for any damages resulting from any virus transmitted. Thank you.PLEASE CONSIDER THE ENVIRONMENT BEFORE YOU PRINT THIS E-MAILAntes de Imprimir pense em sua responsabilidade e compromisso com o MEIO AMBIENTOn 2024-02-23, at 14:45, Rudy Berends ***@***.***> wrote:﻿
I have never tested it with a v2 miniserver, but we can probably make it work. Can you use an ip to connect to the miniserver, or does it have to be an DNS record?
