### ISSUE TITLE
Lock Mechanism: Lock/Unlock swapped

### ISSUE THREAD

**Issue by TheFritz89** [rudyberends/homebridge-loxone-proxy#88]
The lock mechanism shows open when it's closed and wise versa. How can i change this behaviour?

**Comment by rudyberends** [comment]
I assume you are using a switch mapping to translate the Loxone Switch Item to an HomeKit Doorlock right?

The plugin expects te door to be locked when the switch is ON and unlocked when the switch is OFF 
![IMG_0355](https://github.com/rudyberends/homebridge-loxone-proxy/assets/75836217/da9a5b0f-005f-4ea4-9aff-eaf14eecb9c3)

In my case the switch name starts with "Deurslot" and on this picture it is locked.

This can then be mapped in the plugin like this;
<img width="598" alt="Scherm­afbeelding 2024-03-04 om 18 45 51" src="https://github.com/rudyberends/homebridge-loxone-proxy/assets/75836217/71bd9e95-8ead-4b84-b43f-3eb48d448ea1">

Which will give you this result in HomeKit;
![IMG_0357](https://github.com/rudyberends/homebridge-loxone-proxy/assets/75836217/64dbbbe5-135b-48e7-8e68-4f5937559988)

If you are using the mapping, your switch in Loxone probably works the other way around right? You could fix this in Loxone by creating a dummy switch connected to the real switch and using a reversal to give the switch the opposite value. If you have a dedicated Loxone user for the plugin, you could even expose the switch to only the plugin user, so nobody else can see it in the Loxone app. 

We could also make an option in the plugin code to reverse the behavior. This would require a configuration parameter in the config, so you can choose the desired behavior of the switch.

Please let me know if this is the case, and how you would like to handle this. If you prefer a change to the code, we will make this a feature request.

**Comment by TheFritz89** [comment]
Thank you very much for your fast answer and your help

Yes, the switch is mapped as you assumed. The workaround with the dummy switch is working.
<img width="951" alt="SCR-20240304-rnxb" src="https://github.com/rudyberends/homebridge-loxone-proxy/assets/130820027/0bf8bda7-050e-448c-83a5-283a85f0083c">

If you can make it an Option in the config to change the behaviour it would be very nice.

**Comment by rudyberends** [comment]
I released a new beta version v1.10.0-beta.1. This should give you the requested functionality.
Under "switchitem mappings" there is a toggle that reverses the order of the switch. Turning this on should give you a working doorlock on the original switch item.

Please let me know if this is working for you.

**Comment by TheFritz89** [comment]
Thank you very very much for your effort. The solution works perfectly.

Can I buy you a coffee or something to thank you?
