### ISSUE TITLE
Intercom questions

### ISSUE THREAD

**Issue by iniciante** [rudyberends/homebridge-loxone-proxy#9]
Great plugin, thanks sharing.

About the intercom I can see the camera image but is it possible to operate the door opener and the speaker associated?

Thanks a lot.

**Comment by rudyberends** [comment]
The Intercom V2 function block has 3 outputs available that are advertised as push buttons. I suspect you have connected your door opener to one of these outputs?

A new (beta) version of the plugin is available. If you install this, configured intercom outputs will be available within HomeKit. The push buttons are additional services on the camera accessory. If you go to the live view of the camera, you will see a button at the bottom right. Below that are the configured outputs. Is this what you had in mind?

The speaker and microphone option (2 way audio) is a bit more difficult. Currently the plugin uses an mjpg video stream provided by the intercom.

For intercom (2 way audio) functionality, Loxone uses WebRTC and requires a websocket connection to the intercom for WebRTC signaling. This must then be translated into a protocol that is supported by homekit. I do think it is technically possible, but it can take a while and the question is whether the translation process generates so much overhead that there is too much delay in the audio connection, making intercom functionality unusable. Of course you can use more powerful hardware, but I personally think it should be able to run on a raspberry pi or similar hardware.

**Comment by iniciante** [comment]
thanks for your response. Maybe this is stupid question... sorry newbie question... how I can download the beta version?

**Comment by iniciante** [comment]
Thanks a lot. I will check. I am new on home assistant and times is hard...

I am using now HomeKit with a plugin with Loxone working with the camera and rest of the buttons. I would like to have everything in home assistant due most of the integrations are better solved here.

**Comment by iniciante** [comment]
Sorry for this newbie question.... how to install the beta version over the previous. I have uninstalled the integration but the repository downloaded is the last official. I don't know how to play with it...
