### ISSUE TITLE
Multiple FFMPEG instances

### ISSUE THREAD

**Issue by 350d** [rudyberends/homebridge-loxone-proxy#93]
Feature request here.

Let's enable multiple camera instances/streams like in [FFMPEG CAMERA](https://github.com/search?q=repo%3ASunoo%2Fhomebridge-camera-ffmpeg%20maxStreams&type=code).
I have (like many others I guess) multiple devices on my HomeKit network where I can see the Intercom camera preview and right now video stream available only on first device there notification/stream was opened. So, if I have enabled camera notifications/preview on my Apple TV - it will be visible there but same time on my watches or on iPhone I can't see video feed.

Is this possible to implement?
Thanks!

**Comment by rudyberends** [comment]
i forgot to mention it, but could you check the latest beta to see if that works for you?

**Comment by 350d** [comment]
@rudyberends It works! Awesome! Any news about two way audio and HKSV?

**Comment by rudyberends** [comment]
great. I will close this request.

I haven't really worked at the intercom implementation anymore, but I will look into it.
